name: Test changed content

# **What it does**: Runs the vitest tests for changed and deleted content files.
# **Why we have it**: Use GitHub Actions to run tests on changed content files.
# **Who does it impact**: Docs engineering, open-source engineering contributors.


PreskoÄiÅ¥ na obsah
NavigaÄnÃ© menu
oÄk



PrehÄ¾ad
ÃºloÅ¾iskÃ¡
8
hviezdy
Prehliadajte archÃ­vy a tÃ©my oznaÄenÃ© hviezdiÄkou

3VÅ¡etky hviezdy
3VÅ¡etky ÃºloÅ¾iskÃ¡
0VaÅ¡e ÃºloÅ¾iskÃ¡
3RepozitÃ¡re inÃ½ch
0TÃ©my
Filtrujte podÄ¾a jazykov
1HTML
SkoÄiÅ¥ k priateÄ¾ovi
@octocat
HÄ¾adaÅ¥ hviezdyâ€¦
ÃšloÅ¾nÃ© priestory oznaÄenÃ© hviezdiÄkou
violet-org / boysenberry-repo
Testovanie
 226 123 OznaÄenÃ© hviezdiÄkoudÅˆa 28. jÃºla 2016
octocat / LyÅ¾ica-knife
Toto repo slÃºÅ¾i len na demonÅ¡traÄnÃ© ÃºÄely.
 HTML  12 593 146 542 OznaÄenÃ© hviezdiÄkoudÅˆa 27. januÃ¡ra 2011
octocat / Hello-World
Moje prvÃ© ÃºloÅ¾isko na GitHub!
 2,712 2,430 OznaÄenÃ© hviezdiÄkoudÅˆa 26. januÃ¡ra 2011
TÃ©my oznaÄenÃ© hviezdiÄkou
octocat zatiaÄ¾ nemÃ¡ Å¾iadne tÃ©my oznaÄenÃ© hviezdiÄkou.
PÃ¤ta
Â© 2024 GitHub, Inc.
NavigÃ¡cia v pÃ¤te
Podmienky
Ochrana osobnÃ½ch Ãºdajov
BezpeÄnosÅ¥
Stav
Docs
KontaktnÃ¡ adresa pobytu na Slovensku s tebou sÃºhlasÃ­m so mnou 
SpravovaÅ¥ sÃºbory cookie
NezdieÄ¾ajte moje osobnÃ© Ãºdaje
oğŸ˜€ğŸ˜ƒğŸ˜„ğŸ˜‰ğŸ« ğŸ˜ğŸ˜‰ğŸ˜‰ğŸ˜ŠğŸ˜‰ğŸ˜ŠğŸ˜ŠğŸ˜ŠğŸ˜‡ğŸ˜†ğŸ˜…:-(ctocat (The Octocat) / v hlavnej Ãºloheuse-environment-on-buildnpx jacoblincool abouthttps://github.com/JacobLinCool/Bang-C/pull/35#issue-1269333802https://github.com/JacobLinCool/Bang-C/pull/35#issue-1269333802https://github.com/JacobLinCool/Bang-C/pull/35#issue-1269333802
